spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
#        通过服务名称访问服务，并开启小写
          enabled: true
          lower-case-service-id: true
      routes:
        - id: blog
          uri: http://localhost:5502
          predicates:
            - Path=/client
          filters:
            - JwtCheck

        - id: v1
          uri: http://47.104.244.171:8080/gas-web/device/list
          predicates:
            - Path=/gas-web/device/list
          filters:
            - JwtCheck

server:
  port: 5555
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5761/eureka/
#security:
#  basic:
#    enabled: false
logging:
  level:
    org.springframework.cloud.gateway: debug

# hystrix 信号量隔离，3秒后自动超时
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true


